### ISSUE TITLE
Is RSDayFlow support multiple selection?

### ISSUE THREAD

**Issue by andrewSvsg** [ruslanskorb/RSDayFlow#100]

**Comment by aryaxt** [comment]
I have a fork here that allows range selection. Also a branch opened that allows multi selection. I have used range selection in prod, and has no issues with it, but haven't used multi selection in prod yet

**Comment by pvni** [comment]
How can i achive the multiple selection of dates between 2 dates in this calendar?

**Comment by ruslanskorb** [comment]
https://github.com/aryaxt/RSDayFlow/tree/AG/SelectionMode

**Comment by nitisha1** [comment]
How to clone branch using pods?

**Comment by nitisha1** [comment]
Hello , i want to change the color of FirstDate and Last date  as say Color1 and range color to say color2.
How do i achieve this?
Any help pls

**Comment by ruslanskorb** [comment]
No, **RSDayFlow** does not support multiple selection at the moment.
