### ISSUE TITLE
Feature request: Notifications when displayed month changes ?

### ISSUE THREAD

**Issue by cc-lam** [ruslanskorb/RSDayFlow#102]
Hi, I would like to be able to fetch data as the user scrolls and goes from one month to another.  For this, there needs to be some kind of notification that the displayed month has changed so that a fetch can be triggered.

I think one quick solution would be in `RSDFDatePickerView.m`.  In `collectionView(_:viewForSupplementaryElementOfKind:_)` maybe just send an NSNotification with a userInfo containing the date info ? Or maybe call a new delegate method like `didChangeDisplayedMonth` ?

Sorry for not sending a PR, but I'm really not good at ObjC

**Comment by lammertw** [comment]
Hi,

Thanks for your proposal. My suggestion is you subclass `RSDFDatePickerView` which allows you to override/implement methods of `UICollectionViewDelegate` and `UIScrollViewDelegate` in which you can then fetch your data.

Let me know if this helps.

**Comment by cc-lam** [comment]
Yep, much better ... Should have thought about it a little more.  Thanks!
