### ISSUE TITLE
Horizontal Scrolling ?

### ISSUE THREAD

**Issue by plm75** [ruslanskorb/RSDayFlow#105]
Nice library!

Is there any chance to see an option for horizontal scrolling in a future release ?

**Comment by ruslanskorb** [comment]
Unfortunately, I have no time at the moment to implement this feature.
Maybe someone from users of RSDayFlow can do it. It would be nice to see the PR related to this issue.

**Comment by lammertw** [comment]
@plm75 Have a look at my https://github.com/lammertw/PagingDatePicker repository. It's based on RSDayFlow and support horizontal scrolling.

**Comment by plm75** [comment]
@lammertw : thanks, I'll definitely have look.
