### ISSUE TITLE
deselect date on RSDFDatePickerView

### ISSUE THREAD

**Issue by banjun** [ruslanskorb/RSDayFlow#107]
RSDayFlow 1.5.0 has `nonnull` annotation on `RSDFDatePickerView.selectDate` and its selected date highlight cannot be deselected by `selectDate: nil`.
It would be nice if it's `nullable` for nil-deselectable.

**Comment by ruslanskorb** [comment]
@banjun [Fixed!](https://github.com/ruslanskorb/RSDayFlow/releases/tag/1.5.1)

**Comment by banjun** [comment]
:+1:
