### ISSUE TITLE
_calendar should be set earlier.

### ISSUE THREAD

**Issue by b051** [ruslanskorb/RSDayFlow#113]
in method `- (instancetype)initWithFrame:(CGRect)frame calendar:(NSCalendar *)calendar startDate:(NSDate *)startDate endDate:(NSDate *)endDate`
shouldn't the _calendar be set first? cause in `dateWithoutTimeComponents` it is using self.calendar already

**Comment by ruslanskorb** [comment]
Fixed via #114.
