### ISSUE TITLE
shouldHighlightDate interferes with shouldSelectDate

### ISSUE THREAD

**Issue by infinityloop** [ruslanskorb/RSDayFlow#117]
If you return NO on shouldHighlightDate, it also stops the date from being selected. I expected shouldHighlightDate should only control the visual element while shouldSelectDate returns a delegate method call.

**Comment by ruslanskorb** [comment]
This is the default behaviour of the collection view.
If you would to change it you can create a subclass of `RSDFDatePickerView` and override the method `collectionView:shouldHighlightItemAtIndexPath:`.
