### ISSUE TITLE
Bug scrolling to endDate

### ISSUE THREAD

**Issue by AyusSalleh** [ruslanskorb/RSDayFlow#119]
As an example in my project. I use 
startDate = 22/12/2016
endDate = 28/12
Using frame = self.view.bound

But i cant scroll to the end of the date i've set. 
![img_1397](https://cloud.githubusercontent.com/assets/20343677/21398950/741fecfe-c7e4-11e6-8c25-767f7999bdf6.PNG)

**Comment by ruslanskorb** [comment]
Hi @AyusSalleh,

I have checked the calendar with your dates and everything works fine.
Can you provide a test project with this problem?

Thanks!

**Comment by AyusSalleh** [comment]
here is my coding. http://pastebin.com/3tEXHfLg

**Comment by ruslanskorb** [comment]
I noticed that you do not use the original version of RSDayFlow. It can be your problem. Please provide a working test project instead of raw code. Then I'll try to help you.

**Comment by ruslanskorb** [comment]
I will close the issue for now. Feel free to reopen it after providing a working test project.
