### ISSUE TITLE
Swift3/Xcode 8 support

### ISSUE THREAD

**Issue by MortenHN81** [ruslanskorb/RSDayFlow#123]
Hi Im using Xcode8 and cocoapods in a swift 3 project and RSDayFlow is not able to compile. The component looks really great and i hope there will be a fix to this, or maybe even a swift 3 version. Thanks for you hardwork on this awesome component so far :)

Best Regards
Morten

**Comment by ruslanskorb** [comment]
Hi @MortenHN81,

What the problem are you encountered? Can you share what the compiler tells?

**Comment by MortenHN81** [comment]
@ruslanskorb thank you for your quick response, and sorry for the lack of information in my later message. I have added two screenshots of the error in this message. 

![screenshot 2017-06-01 12 35 41](https://cloud.githubusercontent.com/assets/28800345/26676219/28b1508e-46c7-11e7-8e7a-96f42fff2ed5.png)
![screenshot 2017-06-01 12 35 51](https://cloud.githubusercontent.com/assets/28800345/26676220/28b4f662-46c7-11e7-85e9-6558d268e807.png)

Only thing i did was to add pod 'RSDayFlow' to the pod file and run pod install. after that i opened the workspace and build the target the above screenshots are the result of the build.

Really hope you can help me out 

Best Regards
Morten

**Comment by ruslanskorb** [comment]
#122?

What the version of **RSDayFlow** are you using?

**Comment by MortenHN81** [comment]
I have just stated pod 'RSDayFlow' in the podfile so i would guess the newest version ?

**Comment by MortenHN81** [comment]
Hi Again.

When using pod 'RSDayFlow' i cannot build and get the above mention error, if i change it to 'RSDayFlow', '~> 1.6.1' it builds fine. could it be that for some reason pod 'RSDayFlow' dont fetch the latest version ? I have double checked and if i only use pod 'RSDayFlow' the project wont build.

**Comment by ruslanskorb** [comment]
You can try `pod update`. Probably, CocoaPods using the old version of **RSDayFlow** when you are not specifying it explicitly.

**Comment by MortenHN81** [comment]
I believe your right, thank you for your time im looking forward to start playing around with your component.

Best Regards
Morten

**Comment by ruslanskorb** [comment]
:thumbsup:
