### ISSUE TITLE
Want to get month and year when user scroll the calander

### ISSUE THREAD

**Issue by deepakcmbi** [ruslanskorb/RSDayFlow#126]
I have a requirement where i need to call API by passing the Month and Year as soon as user scroll to next or previous month. Can you create a delegate method that return the Month and Year where the scroll is?

I hope i explained it correctly. Let me know if you have any question.

Thanks,
Deepak

**Comment by ruslanskorb** [comment]
You can 1) create a subclass of `RSDFDatePickerView`, 2) override `collectionView:willDisplaySupplementaryView:atIndexPath:` method, 3) get a date using `dateForFirstDayInSection:` method, 4) extract month and year from the date and include them into an API call.

**Comment by deepakcmbi** [comment]
Thanks for your quick and prompt reply.. It would be great if you could help me with the code.. i tried but did not succeeded yet. I will try it tomorrow morning.

Thanks Again :)
