### ISSUE TITLE
Need to change background color on day, depending on the date.

### ISSUE THREAD

**Issue by assembleMHN** [ruslanskorb/RSDayFlow#127]
Hi And thank you for a awesome component.

Im hoping to get some help with a problem that im trying to solve.

Im trying to set the backgroundcolor depending on which date is in the cell. I have not been able to solve this yet, would be great to get some pointers on who to solves this.

What ive have done so far is to make a class that inherited from RSDFDatePickerDayCell and override selfBackgroundColor, and this works fine for making all backgrounds another color. But i only want to change background color on some specific but dynamic days which i hold in a array that i need to compare with. My problem is that when selfBackgroundColor is called "@property (nonatomic, readwrite, assign) RSDFDatePickerDate date;" has not been set yet, so i have no idear what date the specifik cell will contain when the background color is set.

It would also be pretty easy if i had access to the specifik cell in the delegate function, but here only the RSDFDatePickerView is returned, and without any indexpath im not able to fetch the specifik cell to change the background color. Im pretty much stuck here.

Could you guide me through the easiest way to solve this problem ?

Thank you very much for your time!

**Comment by assembleMHN** [comment]
Ive found a solution, i want to hear you if you believe this is the best solution, i think its a bit hacky.

In my subclass of RSDFDatePickerDayCell ive overrided the date property. this way im sure that i dont update the background color before the date is set.

"
    override var date: RSDFDatePickerDate{
        get {
            return super.date
        }
        set{
            super.date = newValue
            self.customBackground()
        }
    }
"

Thank you.

**Comment by ruslanskorb** [comment]
Hi @assembleMHN!

To achieve this you can create a subclass of `RSDFDatePickerView`, override the method `collectionView:cellForItemAtIndexPath:` and make any necessary changes.
To get a date for the specific cell you need to use `dateForCellAtIndexPath:` method of `RSDFDatePickerView`.

**Comment by assembleMHN** [comment]
Hi @ruslanskorb 

Thank you very much for your reply, it worked like a charm:

"
    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let cell = super.collectionView(collectionView, cellForItemAt: indexPath)
        let date = self.dateForCell(at: indexPath)
        let isAbsence = CalendarContentManager.shared.isDateAbsence(date: date)
        
        if isAbsence{
            cell.backgroundColor = UIColor.brown
        }else{
           cell.backgroundColor = UIColor.clear
        }
        
        return cell
    }
"

But i noticed that im gettting colouring of the "empty" dates, please see screenshot

![screen shot 2017-08-17 at 08 11 12](https://user-images.githubusercontent.com/30831333/29398274-ef429a44-8323-11e7-8533-78162f98f6d9.png)

Do you have any idea on how to workaround this ?

Thank you for your time!

**Comment by ruslanskorb** [comment]
@assembleMHN You can check the value of `isNotThisMonth` property of `RSDFDatePickerDayCell`.

```swift
let cell = super.collectionView(collectionView, cellForItemAt: indexPath)
guard cell.isNotThisMonth == false else {
    
    return cell
}
...
```

**Comment by assembleMHN** [comment]
Fantastic, thank you very much this was exactly what i needed. Thank you so much :)
