### ISSUE TITLE
Can we Check scrolling stoped over which Month

### ISSUE THREAD

**Issue by umairjamalian** [ruslanskorb/RSDayFlow#128]
For Example we have to mark some dates for some events, how can we identify current month visible on screen after scrolling stops so that we do the required steps against that.

Waiting for response.

Regards
Umair Jamal

**Comment by ruslanskorb** [comment]
You can create a subclass of `RSDFDatePickerView`, override `scrollViewDidEndDraggin:willDecelerate:` and `scrollViewDidEndDecelerating:` methods, get visible cells and use `dateForCellAtIndexPath:` method to identify the visible month(s).
