### ISSUE TITLE
Is this library have any swift version ?

### ISSUE THREAD

**Issue by siddharthsuneel** [ruslanskorb/RSDayFlow#132]
I want to integrate this library as cocoa pod ink my project which is build in swift 3. I don't want to use bridging header for this purpose.
Is there any swift version of this library avialable ??

**Comment by ruslanskorb** [comment]
I do not provide Swift version of **RSDayFlow**.
To not use a bridging header in your project you can add `use_frameworks!` to your Podfile.

**Comment by siddharthsuneel** [comment]
Thanks @ruslanskorb `use_frameworks!'` was really helpful
