### ISSUE TITLE
Can i change Sat, Sun, date colors as same to other dates ?

### ISSUE THREAD

**Issue by raviguptaibcmobile** [ruslanskorb/RSDayFlow#134]
I really like this library, thank you for making it!
Can I start showing all days in same color?
i mean, i don't want light grey color for sat,sun

**Comment by ruslanskorb** [comment]
Hi @raviguptaibcmobile!

You need to 1) create a subclass of [`RSDFDatePickerDayCell`](https://github.com/ruslanskorb/RSDayFlow/blob/master/Example/RSDayFlowExample/RSDFCustomDatePickerDayCell.h), 2) override [desired properties](https://github.com/ruslanskorb/RSDayFlow/blob/master/Example/RSDayFlowExample/RSDFCustomDatePickerDayCell.m#L55), 3) create a subclass of [`RSDFDatePickerView`](https://github.com/ruslanskorb/RSDayFlow/blob/master/Example/RSDayFlowExample/RSDFCustomDatePickerView.h) and 4) override [`dayCellClass`](https://github.com/ruslanskorb/RSDayFlow/blob/master/Example/RSDayFlowExample/RSDFCustomDatePickerView.m#L55) method.

**Comment by raviguptaibcmobile** [comment]
Thanks for you reply @ruslanskorb.
I'll try the same  you mentioned here.
