### ISSUE TITLE
Not able to disable the older dates from calendar

### ISSUE THREAD

**Issue by sunny131984** [ruslanskorb/RSDayFlow#137]
HI ,

First of all thanks for such wonderful framework.
I am try to add this in my project and i try to disable the older days from calendar.
I try to find but not able to find that feature and actually its available in UIdatePicker components.
By Setting its minimum date.

Please suggest proper way for it.
thanks

**Comment by ruslanskorb** [comment]
Hi @sunny131984,

You can create [a subclass](https://github.com/ruslanskorb/RSDayFlow/blob/master/Example/RSDayFlowExample/RSDFCustomDatePickerDayCell.m) of `RSDFDatePickerDayCell` and set text colors for days that are [out of `startDate` & `endDate` range](https://github.com/ruslanskorb/RSDayFlow/blob/master/RSDayFlow/RSDFDatePickerDayCell.h#L84) to `[UIColor clearColor]`.

Best,
Ruslan
