### ISSUE TITLE
Current date is concatenating when change from islamic calendar to english. 

### ISSUE THREAD

**Issue by veerChauhan** [ruslanskorb/RSDayFlow#138]
i am changing the calendar language , but the current date concatenating with the another one. please help
![unadjustednonraw_thumb_8e4](https://user-images.githubusercontent.com/26132769/40912641-cd042494-680f-11e8-827c-c70dc90e2d08.jpg)

**Comment by ruslanskorb** [comment]
Hi @veerChauhan,

It looks like you are using subclasses instead of the original classes. It's hard to say what the problem is.
Could you reproduce your problem in a test project?

Thanks,
Ruslan

**Comment by ruslanskorb** [comment]
@veerChauhan Feel free to reopen it if the issue still exists.
