### ISSUE TITLE
how can I change the langauge

### ISSUE THREAD

**Issue by DreamRui** [ruslanskorb/RSDayFlow#142]
My iPhone device langauge is English，my app ` Localization native development region` is China. 
when `iPhone langauge` use English, how can I change `week's words`  use Chinese.

![image](https://user-images.githubusercontent.com/9304671/46715938-a4fbed80-cc94-11e8-9815-e9d01477a714.png)

**Comment by ruslanskorb** [comment]
@DreamRui For debugging, you can change the application language in the schema options.

<img width="893" alt="screen shot 2018-10-15 at 09 50 15" src="https://user-images.githubusercontent.com/1182823/46934363-23bfa480-d060-11e8-8333-52212ad12507.png">
