### ISSUE TITLE
Add a blank space listener on RSDatePickerViewDelegate

### ISSUE THREAD

**Issue by Qwerp-Derp** [ruslanskorb/RSDayFlow#143]
I am currently making a calendar view, which overlays a small table view whenever a user clicks on a certain date. It would be convenient for me to have that table view fade out whenever the user clicks on blank space within the app view.

Would it be possible to add a listener for when a user clicks on empty space (i.e. space that isn't occupied by a date) in the RSDatePickerViewDelegate class?

**Comment by ruslanskorb** [comment]
This looks like a specific single app feature and I believe that it will not be widely used. So I decided not to add this functionality to the main repo. But you can always create a fork of **RSDayFlow** and make the necessary changes yourself.

**Comment by Qwerp-Derp** [comment]
I don't really know Objective-C that well - can you point me to where I would have to make changes in order to satisfy what I want to do?
