### ISSUE TITLE
While implementing in swift I got warning and I am unable to give my functionality

### ISSUE THREAD

**Issue by KiranYechuri** [ruslanskorb/RSDayFlow#144]
I have two view controllers.I want to display dates in first view controller label and when I navigate to second VC I want to highlight the value in calendar which was in label.

For the first time user open secondVC to select date I am passing data to firstVC and when user wants to change date I will open secondVC.After opening secondVC whatever the date has selected by user previously that date should be marked as highlighted.
Note:  SecondVC means opening a calendar view controller

**Comment by KiranYechuri** [comment]
warning issue is:
 **warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.**

**Comment by ruslanskorb** [comment]
@KiranYechuri Could you provide a small sample project with your problem?

**Comment by KiranYechuri** [comment]
Some how I was managed to fulfil my requirement.....but one last requirement is I have to show user with his selected date irrespective of month but if month passes away current month I am able to scroll  to specified date but unable to scroll to current month

Current Month : March
e.g.: if a user had selected date in July month then user needs to change his journey date to May month but with your code I am able to scroll directly to July but I am unable to scroll to previous month(march,april,may,june) at the same time...

I had used datepickerview.scroll(to:selectedDate,animated:True/False). Is there any method to fulfill above requirement.I am unable to give sample project as I was implementing it in realtime project.


Any help would be great...........

**Comment by ruslanskorb** [comment]
@KiranYechuri It is very difficult to understand from your description what you are trying to do. Try to describe it in other words or provide a test project.

**Comment by ruslanskorb** [comment]
@KiranYechuri Since your initial problem was solved, I close this task.
