### ISSUE TITLE
wrong selected date

### ISSUE THREAD

**Issue by onuryoeruek** [ruslanskorb/RSDayFlow#146]
Hello,

the datePickerView(_ view: RSDFDatePickerView, didSelect date: Date)-Method is wrong..
if I select 02.05.2019 the date object contains the date 02.05. 
02.05. -> 03.05 
...

I use the latest pod version 1.7.1

**Comment by ruslanskorb** [comment]
Hi @onuryoeruek!

What do you mean by `the date object contains the date 02.05.`?

**Comment by onuryoeruek** [comment]
if I print the selected date inside this method I always get the wrong date..
If I select 02.05 -> I get the date 03.05. and so on...

**Comment by ruslanskorb** [comment]
@onuryoeruek Could you provide a screenshot?

**Comment by onuryoeruek** [comment]
<img width="1680" alt="Bildschirmfoto 2019-05-04 um 11 39 29" src="https://user-images.githubusercontent.com/12371299/57177157-9f007080-6e61-11e9-8dc5-9788fc6bebad.png">

**Comment by ruslanskorb** [comment]
@onuryoeruek `RSDFDatePickerView` displays dates in the time zone of the provided calendar. In turn, Xcode prints `Date` in GMT. Use `DateFormatter` with the correct `locale` to print the right value. You can see how to do it [here](https://github.com/ruslanskorb/RSDayFlow/blob/master/Example/RSDayFlowExample/RSDFDatePickerViewController.m#L214).
