### ISSUE TITLE
Half Screen Calendar with Horizontal Scroll

### ISSUE THREAD

**Issue by faizankhan1909** [ruslanskorb/RSDayFlow#36]
Currently we can only have a full screen calendar view that allows vertical scrolling. I am looking forward to a calendar control that is not covering the full screen and allows horizontal scrolling. What parameters are to be tuned in order to achieve this? Do we have a support for this?

**Comment by ruslanskorb** [comment]
Is there someone who has done it? :-]

**Comment by ruslanskorb** [comment]
Closed for lack of demand.
