### ISSUE TITLE
calendar scroll like paging view

### ISSUE THREAD

**Issue by mohsinalimat** [ruslanskorb/RSDayFlow#47]
Hello,

i want to scroll like a paging in your calendar scroll to add paging like a when i am in month of Nov 2014 then i scroll up and then whole next Dec 2014 month show in view...

**Comment by Objective-Zero** [comment]
I would like to do this do. I played around with pagingEnabled but it doesn't scroll the proper amount. @ruslanskorb Is there specific way of implementing this within your library?
