### ISSUE TITLE
Limit calendar start and end dates

### ISSUE THREAD

**Issue by ShadeApps** [ruslanskorb/RSDayFlow#48]
Is there any convenient way to set the start and the end of the calendar view with, say months from today?

E.g. I want my calendar to show only 3 previous months and 6 future months. Is it possible in the current setup?

**Comment by ShadeApps** [comment]
@serkanucpinar I don't think it's possible to do without changing a bi amount of code base. We've been struggling with it for several weeks now

**Comment by barkiiqbal** [comment]
@ShadeApps  did you succeed to limit start and end dates. Any help please

**Comment by ShadeApps** [comment]
@barkiiqbal We have ended up using MDCalendar - it has the best implementation of start & end dates in iOS open source control right now.

**Comment by barkiiqbal** [comment]
@ShadeApps thanks, i succeed to fix the dates by just commenting the code in pickerCollectionViewWillLayoutSubviews and changing values of toDate and fromDate. Its simple

**Comment by ruslanskorb** [comment]
Is there someone who has done it and can make a pull request? :-]

**Comment by agibson73** [comment]
barkiiqbal, 
Any help on this would be much appreciated.

**Comment by aryaxt** [comment]
@barkiiqbal Mind sharing more info on how you did it? You have a fork somewhere?

**Comment by ruslanskorb** [comment]
Resolved in the version [1.1.0](https://github.com/ruslanskorb/RSDayFlow/releases/tag/1.1.0).
