### ISSUE TITLE
Edit text alert view

### ISSUE THREAD

**Issue by gianlucarpi** [ruslanskorb/RSDayFlow#54]
Hi,
I have set my local notification in the calendar with this code:

- (NSArray *)myLocal
{
    if (!_myLocal) {
        NSCalendar *calendar = [NSCalendar currentCalendar];
        unsigned unitFlags = NSYearCalendarUnit | NSMonthCalendarUnit |  NSDayCalendarUnit ;
        
        NSArray *scheduledLocalNotifications = [[UIApplication sharedApplication] scheduledLocalNotifications];
        NSMutableArray *myLocal = [[NSMutableArray alloc] initWithCapacity:[scheduledLocalNotifications count]];
        for (UILocalNotification *localNotification in scheduledLocalNotifications) {
            NSDateComponents *fireDateComponents = [calendar components:unitFlags fromDate:localNotification.fireDate];
            NSDate *fireDate = [calendar dateFromComponents:fireDateComponents];
            [myLocal addObject:fireDate];
          
        }
        
        _myLocal = [myLocal copy];
    }
    return _myLocal;
}

#pragma mark - RSDFDatePickerViewDataSource

- (BOOL)datePickerView:(RSDFDatePickerView *)view shouldMarkDate:(NSDate *)date
{
    return [self.myLocal containsObject:date];
}

- (BOOL)datePickerView:(RSDFDatePickerView *)view isCompletedAllTasksOnDate:(NSDate *)date
{
    return YES;
}

how can I post the text of the notification in the local alert view?

**Comment by ruslanskorb** [comment]
Hi,

If I understand your question, you can add the following code to your AppDelegate:

```objective-c
- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
{
    UIAlertView *alertView = [[UIAlertView alloc]initWithTitle:@"Notification Received"
                                                       message:notification.alertBody
                                                      delegate:nil
                                             cancelButtonTitle:@"OK"
                                             otherButtonTitles:nil];
    [alertView show];
}
```

Sincerely,
Ruslan

**Comment by gianlucarpi** [comment]
I have solved my problem alone, thank you for your attention.
Gianluca
