### ISSUE TITLE
Issue With Daylight Savings

### ISSUE THREAD

**Issue by ConorLinehan** [ruslanskorb/RSDayFlow#56]
Hi I seem to be having an issue with daylight savings. Where when selecting a date on the date picker view the date returned from 

```ObjectiveC
-(void)dateSelectionViewController:(RSDFDatePickerView *)view didSelectDate:(NSDate *)date
```

Is correct for dates up to the 29th of march i.e logging the NSDate returns for 29th of March returns 2015-03-29 00:00:00 +0000

While logging dates after (example the 30th of march) that returns 2015-03-29 23:00:00 +0000.

Was wondering did anyone have a similar problem?

Thanks.

**Comment by ruslanskorb** [comment]
Hi Conor,

Where did you get this method?
Maybe you mean the following method?
```obj-c
- (void)datePickerView:(RSDFDatePickerView *)view didSelectDate:(NSDate *)date
```
What is locale are you using?
Can you make a fork and demonstrate the problem?

Sincerely,
Ruslan

**Comment by ConorLinehan** [comment]
Sorry I put down the wrong method
```ObjectiveC
-(void)datePickerView:(RSDFDatePickerView *)view didSelectDate:(NSDate *)date
```
The locale is GMT.

I won't be able to make a fork to demonstrate the at the moment since it's company code and I'd need permission. But the version were using is 0.4.0. And Daylight savings is kicking into GMT on the 30th of march which is when the losing of the hour is taking effect.

Thanks a million :)
Conor

**Comment by ruslanskorb** [comment]
IST will be observed in Dublin starting from 29 Mar 2015, 01:00.
As far as I can see, NSLog is giving you the correct answer if your timezone is GMT+1. Midnight your time is 23:00 the day before in GMT.

**Comment by zykis** [comment]
Shouldn't it be
2015-03-29 00:00:00 +0100
rather then
2015-03-29 00:00:00 +0000
?

I'm in Moscow (GMT +3)
And after picking up 06.05.2019
I've got following output:
2019-05-05 21:00:00 +0000
Shouldn't it be
2019-05-05 21:00:00 +0300
or
2019-05-06 00:00:00 +0000
?

**Comment by ruslanskorb** [comment]
@zykis You select the date in the calendar, not the time. `00:00` is the beginning of the day.

`Date` object contains the correct value. It does not care about the years, months, days. It relies on seconds. The value `2019-05-05 21:00:00 +0000` only means that May 6 came 3 hours earlier in your time zone than in the GMT+0.

Let me know how you use the selected date, and maybe I can help you.

**Comment by zykis** [comment]
Particular case: I am using Flight Search library, that provides me with tickets on particular departure date. Since Date object has no information about timezone offset, I guess it takes only yyyy-mm-dd component. And that component in my case pointing to previous day, which is wrong.

**Comment by ruslanskorb** [comment]
@zykis What library and what method are you using? Are they in the public domain? Do you pass the date there as a string or as some other value?

**Comment by zykis** [comment]
https://cocoapods.org/pods/AviasalesSDK
That's one of the biggest flight aggregator in Russia. I pass Date class, not string representation in JRSDKTravelSegmentBuilder.
Aviasales - an app in iOS, that using this library. Not sure if it's available in Latvia's App Store

**Comment by ruslanskorb** [comment]
@zykis As far as I can see, Aviasales uses dates relative to GMT+0. So, specifically for your case, to get the date you need, you must set the `timeZone` of your calendar to `GMT`.
```swift
calendar.timeZone = TimeZone(secondsFromGMT: 0)
```

**Comment by zykis** [comment]
Never work with Calendar directly, but thanks for investigating
