### ISSUE TITLE
Changing Layout Direction

### ISSUE THREAD

**Issue by sdtaheri** [ruslanskorb/RSDayFlow#57]
Hi,

It's a great calendar. The only thing I need is the ability to change the direction of layout. As you know some languages such as Persian or Arabic are written from right to left. I can change the numbers and text to Persian using locale property on NSDateFormatter objects. I need the days to lay themselves out from right to left in each row; let's say 1 is in the right most location and 7 is in the left most and then 8 is in the right most in the 2nd row and so on. I hope you get what I mean and could help me how to do it. @ruslanskorb

**Comment by ruslanskorb** [comment]
Hi @sdtaheri,

The first thing that comes to my mind we need to create a subclass of `RSDFDatePickerCollectionViewLayout`, override the method `layoutAttributesForElementsInRect:` and use basic layout or custom layout depending on the return value of the method `characterDirectionForLanguage:` of the class `NSLocale`.
To change the order of the names of days of the week we need to update the method `layoutWeekdayLabels` of the class `RSDFDatePickerDaysOfWeekView` based on the return value of the method above.

Sincerely,
Ruslan

**Comment by ruslanskorb** [comment]
It would be great if you could add support for RTL languages, because at the moment I don't have a time to work on RSDayFlow.

**Comment by sdtaheri** [comment]
I did this and it seems it works well. If you want, generalize it and add it to your code. I just made it work for Persian in Iran.

In RSDFDatePickerCollectionViewLayout I added this method:

- (NSArray *)layoutAttributesForElementsInRect:(CGRect)rect {
    NSArray *supersAttributes = [super layoutAttributesForElementsInRect:rect];
    NSLocale *currentLocale = [NSLocale localeWithLocaleIdentifier:@"fa_IR"];
    NSLocaleLanguageDirection direction = [NSLocale characterDirectionForLanguage:currentLocale.localeIdentifier];
    
    // if it's an RTL language: change the frame
    if (direction == NSLocaleLanguageDirectionRightToLeft) {
        for (UICollectionViewLayoutAttributes *attributes in supersAttributes) {
            CGRect frame = attributes.frame;
            frame.origin.x = rect.size.width - attributes.frame.size.width - attributes.frame.origin.x;
            attributes.frame = frame;
        }
    }
    return supersAttributes;
}

**Comment by sdtaheri** [comment]
And this is going to work for the week labels: update RSDFDatePickerDaysOfWeekView as in this:

- (void)layoutWeekdayLabels
{
    CGSize itemSize = [self selfItemSize];
    CGFloat interitemSpacing = [self selfInteritemSpacing];
    
    CGFloat y = 0;
    __block CGFloat x = self.frame.size.width - itemSize.width;
    
    NSLocaleLanguageDirection direction = [NSLocale characterDirectionForLanguage:self.calendar.locale.localeIdentifier];

    if (direction == NSLocaleLanguageDirectionRightToLeft) {
        self.weekdayLabels = self.weekdayLabels.reverseObjectEnumerator.allObjects;
    }
    
    [self.weekdayLabels enumerateObjectsUsingBlock:^(UILabel *weekdayLabel, NSUInteger idx, BOOL *stop) {
        CGRect weekdayLabelFrame = CGRectMake(x, y, itemSize.width, itemSize.height);
        weekdayLabel.frame = weekdayLabelFrame;
        if (direction == NSLocaleLanguageDirectionRightToLeft) {
            x -= (itemSize.width + interitemSpacing);
        } else {
            x += (itemSize.width + interitemSpacing);
        }
    }];
}

**Comment by ruslanskorb** [comment]
Thanks, @sdtaheri! :+1: I'll add it to RSDayFlow.
p.s. you need to fix the method `layoutWeekdayLabels`, because `self.weekdayLabels = self.weekdayLabels.reverseObjectEnumerator.allObjects` is not correct. I'll fix it before adding to my code.

Cheers,
Ruslan

**Comment by sdtaheri** [comment]
What's the problem of self.weekdayLabels.reverseObjectEnumerator.allObjects?
This single line of code reverses an NSArray instance. I'm using it and it works. 
By this line of code, I reverse the order of labels (a.k.a make them RTL) and let the other parts do their job

**Comment by ruslanskorb** [comment]
@sdtaheri The method `updateWeekdayLabels` is called after the method `layoutWeekdayLabels`, but the order of the weekday symbols is not changed. As a result, we will have the wrong order of days of the week.
