### ISSUE TITLE
Set default date

### ISSUE THREAD

**Issue by satoship** [ruslanskorb/RSDayFlow#59]
I want to set default date to `RSDFDatePickerView` instead of today. I tried 2 ways:

1) Call `[RSDFDatePickerView selectDate]` in `viewDidLoad`

This is not working with iPhone 6 and it displays 8 days in week.
Because it sets 375px to width of `self.collectionView.frame` in `[RSDFDatePickerView layoutSubviews]`, but the width of collectionView is still 320 when `[RSDFDatePickerView selectDate]` is called.

2) Call `[RSDFDatePickerView selectDate]` in `layoutSubviews` of sub class of RSDFDatePickerView after calling `[super layoutSubviews]`

This is not working and it displays this month.
Because `[visibleCells count]` returns 0 in `scrollToDate` after `[RSDFDatePickerView layoutSubviews]` calls `[self scrollToToday:NO]`.

**Comment by ruslanskorb** [comment]
Hi Satoshi Takada,

I could not reproduce your bug with 8 days in week on iPhone 6. Can you demonstrate this problem on a test project?

To select and scroll a calendar to the specific date (set default date) before appearing you can use the following code in the method `viewDidLoad` of your controller.

```objective-c
NSDate *thirtyDaysBeforeToday = [NSDate dateWithTimeIntervalSinceNow:-(60 * 60 * 24 * 30)];
[self.datePickerView selectDate:thirtyDaysBeforeToday];
[self.datePickerView scrollToDate:thirtyDaysBeforeToday animated:NO];
```

It works properly in the example project.

**Comment by satoship** [comment]
I solved this problem. I am using AutoLayout and `self.datePickerView.frame` is not fixed in `viewDidLoad ` of my controller yet. So I write the following code before previous your code and it is working.

```objective-c
self.datePickerView.frame.size.width = self.view.frame.size.width
```

Thank you for your help!
