### ISSUE TITLE
Add Customization Hooks

### ISSUE THREAD

**Issue by ConorLinehan** [ruslanskorb/RSDayFlow#61]
Hi @ruslanskorb , love RSDayFlow using it at work for our app.

I recently came across a situation were we needed multiple states for a date depending on condition. The way we achieved this is by passing in an NSNumber for the marked parameter instead of a BOOL

```Objective-C
- (NSNumber *)datePickerView:(RSDFDatePickerView *)view shouldMarkDate:(NSDate *)date;
```
and then comparing these values in the ```(UIImage *)customCompleteMarkImage``` method.

Was wondering how you'd feel to a pull request incorporating this type of method (but a bit better done) to add more customization points to the dates? And if you were agreeable with this what type of approach would you advise taking ?? :smiley:  
![image1](https://cloud.githubusercontent.com/assets/5772795/6882307/a2aa3734-d577-11e4-93c3-f6e372603790.PNG)

**Comment by ruslanskorb** [comment]
Hi @ConorLinehan,

I think it would be better to replace the method `datePickerView:isCompletedAllTasksOnDate:` by methods `datePickerView:markImageColorForDate:` and 'datePickerView:markImageForDate:'.

What do you think about it?

**Comment by ConorLinehan** [comment]
@ruslanskorb 
Yeah definitely would add more customization point's if you could just pass in a color marker with your date.

Also looking at another app that uses an infinite scrolling calender (Note the marks under the 29th 6th 9th and 28th)
![image1](https://cloud.githubusercontent.com/assets/5772795/6883654/df50cf32-d5b7-11e4-88b4-6c4244b5f31a.PNG)

A future plan might be to add flags to determine images rendered using NS_OPTIONS thoughts??

**Comment by ruslanskorb** [comment]
@ConorLinehan Sorry, but why do we need it?

**Comment by Objective-Zero** [comment]
+1 for this as it would be very useful
