### ISSUE TITLE
Refresh calendar

### ISSUE THREAD

**Issue by gianlucaSitip** [ruslanskorb/RSDayFlow#63]
hi,i've used your calendar to setting in it a local notification up each date!When i try to add or delete one it doesn't refresh the small green points.It does only when i close and reopen the app.I don't understand what's missing in viewdidappear.How can i do the refresh on the calendar without close and open the app?

**Comment by ruslanskorb** [comment]
To refresh data in the calendar you can use the method `reloadData` of `RSDFDatePickerView`.
