### ISSUE TITLE
Can it show the first day from Monday?

### ISSUE THREAD

**Issue by umekun123** [ruslanskorb/RSDayFlow#64]
I really like this library, thank you for making it!
Can I start showing the first day from Monday instead of Sunday?

I want to show the Monday date in the left side.

**Comment by ruslanskorb** [comment]
Hi Non Umemoto,

Sorry for the delay.
By default, RSDayFlow displays the first day of the week depending on the specified locale of the current calendar.
For example, for the 'en_US' locale the first day of the week is Sunday, but for the 'ru_RU' locale the first day of the week is Monday.
If you want to change this behaviour, you can set the property `firstWeekday` of the calendar to `2`.
As result, Monday is the first day of the week for the 'en_US' locale.

```obj-c
// ------------------
// Gregorian calendar
// ------------------

RSDFDatePickerViewController *gregorianVC = [[RSDFDatePickerViewController alloc] init];
gregorianVC.calendar = [[NSCalendar alloc] initWithCalendarIdentifier:NSCalendarIdentifierGregorian];
gregorianVC.calendar.locale = [NSLocale localeWithLocaleIdentifier:@"en_US"];
gregorianVC.calendar.firstWeekday = 2;
UINavigationController *gregorianNC = [[UINavigationController alloc] initWithRootViewController:gregorianVC];
```

Sincerely,
Ruslan

**Comment by umekun123** [comment]
Cool!  Thanks for your reply!

**Comment by ruslanskorb** [comment]
You are welcome!
