### ISSUE TITLE
Support init without frame

### ISSUE THREAD

**Issue by vikfroberg** [ruslanskorb/RSDayFlow#66]
One should be able to use `[[RSDFDatePickerView alloc] init]` and then set the frame in `- (void)viewDidLayoutSubviews`.

I'll probably take a stab at this in a couple of days.

**Comment by vikfroberg** [comment]
Calling commonInitializer isn't enought. Can't select and scroll to date in viewDidLoad.

**Comment by ruslanskorb** [comment]
Hi Viktor,

In which case you want to initialize the calendar without a frame?

**Comment by ruslanskorb** [comment]
Any news on this?

**Comment by vikfroberg** [comment]
Sorry for late answer.

I've always been using init instead of initWithFrame, the reasoning for this is to avoid duplication of frame logic. I only need to define the layout in layoutsubviews and not in viewdidload.

But it seems that initWithFrame is one of the designated initializers for views so maybe I'm doing it wrong.

**Comment by ruslanskorb** [comment]
I think that we should use the method `initWithFrame:` instead of `init`, because it is the default initializer for `UIView`. Otherwise, we have to select and scroll to date after setting the correct frame.
In your case to support initialization without a frame I can suggest to use the following code (but this is not the best solution in my opinion):

```objective-c
- (void)viewWillLayoutSubviews
{
    [super viewWillLayoutSubviews];
    
    CGRect oldDatePickerViewFrame = self.datePickerView.frame;
    self.datePickerView.frame = self.view.bounds;
    
    if (CGRectIsEmpty(oldDatePickerViewFrame) ) {
        NSDateComponents *todayComponents = [self.calendar components:(NSCalendarUnitYear | NSCalendarUnitMonth | NSCalendarUnitDay) fromDate:[NSDate date]];
        NSDate *today = [self.calendar dateFromComponents:todayComponents];
        [self.datePickerView scrollToDate:today animated:NO];
        [self.datePickerView selectDate:today];
    }
}
```
