### ISSUE TITLE
Use trait collection to decide which form of weekday symbols should be used

### ISSUE THREAD

**Issue by xhacker** [ruslanskorb/RSDayFlow#68]
Currently RSDayFlow uses `isPhone` and `isPortraitInterfaceOrientation` to decide the form of weekday symbols. It mostly fine, but has problems when the view is in split view.

![screen shot 2015-06-15 at 11 03 04 am](https://cloud.githubusercontent.com/assets/1051813/8166705/50c64bfa-134e-11e5-9f52-253d1bda38fc.png)

The best way is to use trait collection. However it requires iOS 8. Another workaround is to use the width of the view. Thoughts?

**Comment by ruslanskorb** [comment]
We can try to have another look at [this PR](https://github.com/ruslanskorb/RSDayFlow/pull/41) or add support for trait collection on devices with iOS 8+.

**Comment by ruslanskorb** [comment]
Hi @xhacker,
Are you planning to make any PR for this?

**Comment by xhacker** [comment]
Is it acceptable to support only iOS 8+?

**Comment by xhacker** [comment]
I just looked at [this PR](https://github.com/ruslanskorb/RSDayFlow/pull/41) and realized it's very flexible. I could make a PR based on that without using trait collection. But I don't have time until this weekend.

**Comment by ruslanskorb** [comment]
Okay, I'll do it myself.

**Comment by xhacker** [comment]
Okay, thanks!

**Comment by ruslanskorb** [comment]
No probs!

**Comment by xhacker** [comment]
Awesome, thanks! :+1:
