### ISSUE TITLE
scrollToDate in viewDidLoad

### ISSUE THREAD

**Issue by satoship** [ruslanskorb/RSDayFlow#74]
I like to use RSDayFlow.

I am calling `scrollToDate` in `viewDidLoad`. This is working with 0.8.0, but this is not working with 0.9.0. I think 757f250062df6c42cd5bb4e34446ce52aaf3c1da is related to this behavior.

When I tried to call `scrollToDate` in `viewDidLayoutSubviews`, it is working. Is this correct behavior?

**Comment by ruslanskorb** [comment]
Hi @satoship!
Version 1.1.0 will fix it :-] You can continue to call the method `scrollToDate:animated:` in the method `viewDidLoad`.

**Comment by satoship** [comment]
Thanks.
