### ISSUE TITLE
Sreevijitha

### ISSUE THREAD

**Issue by Sreevijitha** [ruslanskorb/RSDayFlow#84]
I have implemented the RSDayFlow Calendar, it is awesome. In my project need to specify the Start and end Date. Is that possible? Thanks in advance for any help you are able to provide.

**Comment by ruslanskorb** [comment]
Yes, it is. But currently there is only one way to achieve this. You need to use the method `initWithFrame:calendar:startDate:endDate:` of `RSDFDatePickerView`.
In the next version we will move the property `calendar`, the property `startDate` and the property `endDate` to the public API. So you will be able to change them after initialization of the view from storyboard or xib.

**Comment by Sreevijitha** [comment]
Thank you for your response Ruslanskorb . Now its working...

**Comment by ruslanskorb** [comment]
@Sreevijitha :thumbsup:
