### ISSUE TITLE
Selecting First Day of each month and today's date of current month

### ISSUE THREAD

**Issue by RajChanchal** [ruslanskorb/RSDayFlow#86]
Is there anyway to select 1st date of each month and today's date of current month? So that if I scroll up or down, they months's appropriate dates (1st for other months and today's date for current month) remain pre-selected. This is same behaviour as in iCalendar.

**Comment by ruslanskorb** [comment]
RSDayFlow does not provide this functionality.
p.s. Personally, I think that this is not a good idea.
