### ISSUE TITLE
Date highlight only when pressed?

### ISSUE THREAD

**Issue by anderkh** [ruslanskorb/RSDayFlow#90]
When I press a date, the date is highlighted, but when I selected it programmatically, it isn't.  Is there a way to highlight the selected date as if it had been pressed?

Thanks

**Comment by ruslanskorb** [comment]
Sorry, but I don't quite understand your question.
Currently to highlight the date the user can simply tap on the cell. It will work in both cases. When the cell is selected or not.

**Comment by anderkh** [comment]
My apologies.  The actual problem has to do with time zones, not selection.  When sending in a date that is GMT, it seems like it's converting to local time, therefore highlighting the previous date instead.  Is it possible to modify this to respect the timezone of the NSDate?

**Comment by ruslanskorb** [comment]
I suppose that it is your case - http://stackoverflow.com/questions/7485493/get-nsdate-from-nsdate-adjusted-with-timezone

Cheers!
