### ISSUE TITLE
Wrong selection bounds check

### ISSUE THREAD

**Issue by keithyip** [ruslanskorb/RSDayFlow#94]
self.toDate is exclusive. When self.selectedDate is the same as self.toDate, there will be out of bounds crash in the collection view. The check is
[self.selectedDate compare:[self dateFromPickerDate:self.toDate]] != NSOrderedDescending
but it should be
[self.selectedDate compare:[self dateFromPickerDate:self.toDate]] == NSOrderedAscending

**Comment by ruslanskorb** [comment]
@keithyip Which version of RSDayFlow are you using? The latest stable version does not contain the code you specified.

**Comment by keithyip** [comment]
I am using an old version but the logic is still in the master. The file is RSDFDatePickerView.m. The latest code is
`[self.selectedDate compare:self.toDate] != NSOrderedDescending`
I briefly checked the number of sections. The logic looked wrong.

**Comment by ruslanskorb** [comment]
@keithyip It would be better if you provide an example project with your problem.
Why do you think that `self.toDate` should be exclusive?
On which line your app crashes?

**Comment by keithyipkw** [comment]
I created an example project (with submodule)  https://github.com/keithyipkw/RSDayFlowIssue94
I need to access the layout attribute so I discovered the out of bounds problem.

**Comment by ruslanskorb** [comment]
@keithyipkw Thanks man!
[Fixed.](https://github.com/ruslanskorb/RSDayFlow/releases/tag/1.4.0)
