### ISSUE TITLE
Is it possible to make "sticky" month's header 

### ISSUE THREAD

**Issue by Insider77** [ruslanskorb/RSDayFlow#96]
Hi! Thanks for this great calendar!
Is it possible to make "sticky" month's header like a section header in UITableView?

**Comment by ruslanskorb** [comment]
Hi, @Insider77!

To achieve this you need to create and use a custom layout for the `RSDFDatePickerCollectionView`.
[It](https://gist.github.com/toblerpwn/5393460) may be helpful for you.

**Comment by Insider77** [comment]
Thank you! I'll try it

**Comment by xuanzi23** [comment]
@Insider77 Do you manage to do it? I also wanted to make it sticky month header
