### ISSUE TITLE
Change text colors on specific dates

### ISSUE THREAD

**Issue by jfclifton** [ruslanskorb/RSDayFlow#97]
I would like to change the text color on specific dates. I see that I can change some of the text colors for weekends or days of week but I would like to change individual date colors. What's the best way of going about this?

**Comment by ruslanskorb** [comment]
Hi @jfclifton!
To achieve this you can create a subclass of `RSDFDatePickerView`, override the method `collectionView:cellForItemAtIndexPath:` and make any necessary changes.
